version: '3.8'

services:
  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    ports:
      - "8024:8024"  # Axon Dashboard
      - "8124:8124"  # Axon gRPC
    volumes:
      - axonserver-data:/data
      - axonserver-eventdata:/eventdata

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: axon_db
      MYSQL_USER: axon
      MYSQL_PASSWORD: axonpassword
    ports:
      - "3306:3306"

volumes:
  axonserver-data:
  axonserver-eventdata:
  mongodb_data:
